/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BidItem: typeof import('./src/components/lists/bidItem.vue')['default']
    CommonFooter: typeof import('./src/components/common/commonFooter.vue')['default']
    CommonHeader: typeof import('./src/components/common/commonHeader.vue')['default']
    EmailVerify: typeof import('./src/components/common/emailVerify.vue')['default']
    Exchangelist: typeof import('./src/components/lists/exchangelist.vue')['default']
    ExchangeSearch: typeof import('./src/components/common/exchangeSearch.vue')['default']
    FooterItem: typeof import('./src/components/common/footerItem.vue')['default']
    ListItem: typeof import('./src/components/lists/listItem.vue')['default']
    ListItemBAK: typeof import('./src/components/lists/listItemBAK.vue')['default']
    ListSearch: typeof import('./src/components/common/listSearch.vue')['default']
    OrderDialog: typeof import('./src/components/vdialog/orderDialog.vue')['default']
    Recordlist: typeof import('./src/components/lists/recordlist.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanImagePreview: typeof import('vant/es')['ImagePreview']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPagination: typeof import('vant/es')['Pagination']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTimePicker: typeof import('vant/es')['TimePicker']
    VanUploader: typeof import('vant/es')['Uploader']
    VbtnDialog: typeof import('./src/components/vdialog/vbtnDialog.vue')['default']
    Withdrawlist: typeof import('./src/components/lists/withdrawlist.vue')['default']
    WithdrawSearch: typeof import('./src/components/common/withdrawSearch.vue')['default']
  }
}
